name: Continuous Integration Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }} # This line was previously written in `run pipeline` stage

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip dependencies # Caching mechanism to speed up dependency installation
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Pull data from DVC
        run: |
          dvc pull

      - name: run pipeline
        run: |
          dvc repro

      - name: Run model tests
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        run: |
          python Scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        run: python -m unittest tests/test_flask_app.py

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection:latest .

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection:latest

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:5000 -e DAGSHUB_PAT=3790e6632f300b1ba8c9502580aab4c7818da7ab ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection:latest
